# Generated by Django 2.2.28 on 2025-03-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momentum25', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='agree_policy',
            field=models.BooleanField(default=False),
        ),
    ]
